// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Reforce_annaBotML.Model
{
    public class ModelInput
    {
        [ColumnName("PHRASE"), LoadColumn(0)]
        public string PHRASE { get; set; }


        [ColumnName("INTENTION"), LoadColumn(1)]
        public string INTENTION { get; set; }


    }
}
